config/routes.rb
PictureApp::Application.routes.draw do
  root :to => 'pages#home'
  get '/about' => 'pages#about'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  get '/search' => 'search#search'


  get     '/categories/add_user_to_categories/:id/edit' => 'categories#edit_user_categories', :as => 'edit_user_to_categories'
  post     '/categories/add_user_to_categories' => 'categories#add_user_to_categories'
  get    '/categories/:id/edit' => 'categories#edit', :as => 'edit_category'
  get    '/categories/new' => 'categories#new', :as => 'new_category'
  post    '/categories/:id' => 'categories#create'
  get    '/categories/:id' => 'categories#show', :as => 'category'
  put    '/categories/:id' => 'categories#update'
  delete '/categories/:id' => 'categories#destroy'


  get '/picture/:id/favourite' => 'pictures#favourite', :as => 'favourite'
  delete '/picture/:id/favourite' => 'pictures#destroy_favourite', :as => 'destroy_favourite'

  get '/users/:id/favourites' => 'users#favourites', :as => 'favourites'


  resources :pictures
  resources :users, :except => [:edit] do
    collection do
      get 'edit'
    end
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string(255)
#  email           :string(255)
#  image           :string(255)
#  password_digest :string(255)
#  is_admin        :boolean
#  user_ids        :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#


class User < ActiveRecord::Base
  has_secure_password

  attr_accessible :username, :email, :image, :password, :password_confirmation, :is_admin, :remote_image_url #, :user_ids

  mount_uploader :image, PictureUploader

  has_many :pictures
  has_many :favourites
  has_and_belongs_to_many :categories

  validates :email, :presence => true
  validates :email, :uniqueness => true
  validates :username, :presence => true, :length => { :minimum => 3 }
  validates :password, :length => { :minimum => 6 }

  def owned_categories
    Category.where :owner_id => self.id
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :check_if_logged_in, :except => [:new, :create]
  before_filter :check_if_admin, :only => [:destroy]

  def index
    @users = User.all
    @user = @authenticated
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new params[:user]


    if @user.save
      session[:user_id] = @user.id
      category = Category.create :name => 'All', :owner_id => @user.id
      category.users = User.all
#wishlist- add future users
      redirect_to pictures_path

    else
      render :new
    end


  end

  def edit
    @user = @authenticated
    render :new
  end

  def update
    @user = @authenticated
    if @user.update_attributes params[:user]
      redirect_to user_path(@authenticated)
    else
      render :new
    end
  end

  def show
    @user = User.find params[:id]
    @picture = Picture.new
  end

  def favourites
    @user = User.find params[:id]
    @favourites = @user.favourites
  end



  private
  def check_if_logged_in
    redirect_to(root_path) unless @authenticated.present?
  end

  def check_if_admin
    redirect_to(root_path) unless @authenticated.present? && @authenticated.is_admin?
  end
end

app/views/users/_sidenav.html.erb
<div class="col-md-2 col-md-push-10">
  <h2 class="username"><%= link_to user.username, user_path(@authenticated) %> </h2>

  <%= link_to (image_tag user.image_url, class: "user_img"), user_path(@authenticated) %>

  <div class="btn-group-vertical">
      <%= link_to 'Edit Profile', edit_users_path, class: "btn btn-default dropdown-toggle" %>
      <%= link_to 'My Favourites', "/users/#{user.id}/favourites", class: "btn btn-default dropdown-toggle" %>
      <%= link_to 'New Picture', new_picture_path, class: "btn btn-default dropdown-toggle" %>
      <%= link_to 'New Category', new_category_path, class: "btn btn-default dropdown-toggle" %>

    <h5 class="btn btn-default dropdown-toggle heading"><strong>Categories:</strong></h4>
      <% user.owned_categories.each do |category| %>
        <%= link_to category.name, category_path(category), class: "btn btn-default dropdown-toggle", :title => category.name %>
      <% end %>
  </div>
</div>

app/views/users/favourites.html.erb
<div class="row">
  <%= render :partial => 'users/sidenav', :locals => {:user => @authenticated} %>
  <div class="col-md-10 col-md-pull-2">
    <div class="row">
      <div class="col-xs-12 col-md-10">
        <h2>My Favourites</h2>
          <% @favourites.each do |favourite| %>
              <%= render :partial => 'pictures/picture', :locals => {:picture => favourite.picture}  %>
          <% end %>
      </div>

        <%= render :partial => 'sidenav', :locals => {:user => @authenticated} %>
    </div>
  </div>

</div>

app/views/users/index.html.erb
<div class="row">
  <%= render :partial => 'sidenav', :locals => {:user => @authenticated} %>
  <div class="col-md-10 col-md-pull-2">
    <h2>Glimpsed Users</h2>

      <% @users.each do |user| %>
      <div class="col-sm-6 col-md-3">
        <div class="user_index">
          <h3><%= link_to user.username, user_path(user) %> </h3>
          <%== link_to raw("<div class='thumbnail' style='background-image:url(#{user.image_url})'></div>"), user_path(user) %>
        </div>
      </div>
      <% end %>
  </div>

</div>

app/views/users/new.html.erb
      <% if @user.id.present? %>
        <h2>Edit Your Profile</h2>
      <% else %>
        <h2>Become a new user</h2>
      <% end %>

      <% if @user.errors.any? %>
        <ol>
          <% @user.errors.full_messages.each do |msg| %>
            <li class="alert alert-warning"><%= msg %></li>
          <% end %>
        </ol>
      <% end %>

      <div class="new_user_form">
        <%= form_for @user, :html => {:multipart => true} do |f| %>

          <div class='form-group'>
            <%= f.label :username %>
            <%= f.text_field :username, :autofocus => true, :class => 'form-control', :placeholder => 'Required' %>
          </div>
          <div class='form-group'>
            <%= f.label :email %>
            <%= f.text_field :email, :class => 'form-control', :placeholder => 'Required' %>
          </div>

          <div class="user_edit_img"><%= image_tag @user.image_url if @user.image? %></div>

          <div class='form-group'>
            <%= f.label :image %>
            <%= f.file_field :image %>
          </div>
          <div class='form-group'>
            <%= f.label :remote_image_url, "Or Picture Url" %>
            <%= f.text_field :remote_image_url, :class => 'form-control', :placeholder => 'Optional' %>
          </div>
          <div class='form-group'>
            <%= f.label :password %>
            <%= f.password_field :password, :class => 'form-control', :placeholder => 'Required' %>
          </div>
          <div class='form-group'>
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, :class => 'form-control', :placeholder => 'Required' %>
          </div>
          <%= f.submit %>
        </div>
      <% end %>

app/views/users/show.html.erb
<div class="row">
  <%= render :partial => 'sidenav', :locals => {:user => @authenticated} %>
  <div class="col-md-10 col-md-pull-2">
    <% if @user.id != @authenticated.id %>
      <h2 class="show_user"><%= @user.username %> </h2>
      <h3><%= link_to 'Add to a Category', edit_user_to_categories_path(@user) %></h3>
      <h2 class="show_user"><%= image_tag @user.image %></h2>
      <h2><%= @user.username %>'s Pictures </h2>
    <% else %>
      <h2>My Pictures</h2>
    <% end %>

    <%= render :partial => 'pictures/picture', :collection => @user.pictures %>
  </div>

</div>