config/routes.rb
PictureApp::Application.routes.draw do
  root :to => 'pages#home'
  get '/about' => 'pages#about'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  get '/search' => 'search#search'


  get     '/categories/add_user_to_categories/:id/edit' => 'categories#edit_user_categories', :as => 'edit_user_to_categories'
  post     '/categories/add_user_to_categories' => 'categories#add_user_to_categories'
  get    '/categories/:id/edit' => 'categories#edit', :as => 'edit_category'
  get    '/categories/new' => 'categories#new', :as => 'new_category'
  post    '/categories/:id' => 'categories#create'
  get    '/categories/:id' => 'categories#show', :as => 'category'
  put    '/categories/:id' => 'categories#update'
  delete '/categories/:id' => 'categories#destroy'


  get '/picture/:id/favourite' => 'pictures#favourite', :as => 'favourite'
  delete '/picture/:id/favourite' => 'pictures#destroy_favourite', :as => 'destroy_favourite'

  get '/users/:id/favourites' => 'users#favourites', :as => 'favourites'


  resources :pictures
  resources :users, :except => [:edit] do
    collection do
      get 'edit'
    end
  end
end

app/views/pages/about.html.erb
<p>This page is about me</p>

app/views/pages/home.html.erb
<div class="row">


  <div class="marketing col-md-3">
            <h2>Welcome to Glimpsed</h2>
            <p>It is home to the best shots in your collection, the pictures that tell your story, the photographs you will always treasure. Special moments, glimpsed for an instant.</p>
            <p><%= link_to 'Explore', pictures_path, :class => "btn btn-default", :role => "button" %></p>
  </div><!-- marketing /.col-lg-3 -->



  <div class="col-md-6">

    <h1>Glimpsed</h1>
    <h1 class="sub_title">Special moments, glimpsed for an instant</h3>


      <!-- Carousel
      ================================================== -->
      <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <% active = "active" %>
          <% @pictures.each do |picture| %>
          <div class="item <%= active %>" style='background-image:url(<%= picture.picture_url %>)'></div>
            <% active = '' %>
          <% end %>
        </div>
        <a class="left carousel-control" href="#myCarousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
      </div><!-- /.carousel -->
  </div>



  <div class="marketing col-md-3 signup">
    <% unless @authenticated.nil? %>
            <h2>My Profile</h2>
            <p>Dive into Glimpsed to add new pictures, tell a photographic story, edit your profile and create new categories.  </p>
            <p><%= link_to 'My Profile', user_path(@authenticated), :class => "btn btn-default", :role => "button" %></p>
    <% else %>
            <h2>Sign Up</h2>
            <p>Join the Glimpsed community. Sign up and share in the passion and enjoyment.  </p>
            <p><%= link_to 'Create Account', new_user_path, :class => "btn btn-default", :role => "button" %></p>
    <% end %>
  </div><!-- marketing /.col-lg-3 -->


</div><!-- /.row -->