config/routes.rb
PictureApp::Application.routes.draw do
  root :to => 'pages#home'
  get '/about' => 'pages#about'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  get '/search' => 'search#search'


  get     '/categories/add_user_to_categories/:id/edit' => 'categories#edit_user_categories', :as => 'edit_user_to_categories'
  post     '/categories/add_user_to_categories' => 'categories#add_user_to_categories'
  get    '/categories/:id/edit' => 'categories#edit', :as => 'edit_category'
  get    '/categories/new' => 'categories#new', :as => 'new_category'
  post    '/categories/:id' => 'categories#create'
  get    '/categories/:id' => 'categories#show', :as => 'category'
  put    '/categories/:id' => 'categories#update'
  delete '/categories/:id' => 'categories#destroy'


  get '/picture/:id/favourite' => 'pictures#favourite', :as => 'favourite'
  delete '/picture/:id/favourite' => 'pictures#destroy_favourite', :as => 'destroy_favourite'

  get '/users/:id/favourites' => 'users#favourites', :as => 'favourites'


  resources :pictures
  resources :users, :except => [:edit] do
    collection do
      get 'edit'
    end
  end
end

app/models/picture.rb
# == Schema Information
#
# Table name: pictures
#
#  id          :integer          not null, primary key
#  picture     :text
#  description :string(255)
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  name        :string(255)
#

class Picture < ActiveRecord::Base
  attr_accessible :picture, :description, :user_id, :name, :remote_picture_url

  mount_uploader :picture, PictureUploader

  belongs_to :user
  has_many :favourites

  validates :picture, :presence => true

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  def index
    @pictures = Picture.all
  end

  def new
    @picture = Picture.new
  end

  def create

    @picture = Picture.new params[:picture]
    @picture.user = @authenticated

    if @picture.save
      redirect_to picture_path(@picture)
    else
      render 'new'
    end
  end


  def edit
    @picture = Picture.find params[:id]
    if @picture.user_id != @authenticated.id
      redirect_to picture_path(@picture)
    else
      render :new
    end
  end

  def update
    picture = Picture.find params[:id]
    if picture.user_id != @authenticated.id
      redirect_to picture_path(picture)
    end

    if picture.update_attributes params[:picture]
      redirect_to picture_path(picture)
    else
      render :new
    end
  end

  def show
    @picture = Picture.find params[:id]
  end

  def destroy
    picture = Picture.find params[:id]
    if picture.user_id != @authenticated.id
      redirect_to user_path(@authenticated)
    end
    picture.destroy
    redirect_to user_path(@authenticated)
  end


  def favourite
    favourite = Favourite.create :picture_id => params[:id], :user_id => @authenticated.id
    redirect_to :back
  end

  def destroy_favourite
    favourite = Favourite.where(:picture_id => params[:id], :user_id => @authenticated.id).first
    favourite.destroy
    redirect_to :back
  end

end

app/views/pictures/_picture.html.erb
  <div class="col-sm-6 col-md-3">
    <div class="thumbnail_container">

      <%== link_to raw("<div class='thumbnail' style='background-image:url(#{picture.picture_url})'></div>"), picture_path(picture) %>
      <div class="caption">

        <p class="thumb_cap"><%= picture.name %></p>
        <h4 class="thumb_cap pull-left"><%= link_to picture.user.username, user_path(picture.user) %></h4>
        <% if @authenticated.present? %>
          <% if picture.id.in? @authenticated.favourites.map &:picture_id %>
            <%= button_to 'Unfavourite', favourite_path(picture), :method => 'delete', :class => 'pull-right' %>
          <% else %>
            <%= button_to 'Favourite!', favourite_path(picture), :method => 'get', :class => 'pull-right' %>
          <% end %>
        <% end %>
      </div>
    </div>
</div>

app/views/pictures/index.html.erb
<h1> </h1>

<h4>These photos are Glimpsed. Upload your own own or return to discover new Glimpses. </h4>

     <%= render :partial => 'picture', :collection => @pictures.shuffle %>

app/views/pictures/new.html.erb
<div class="row">
  <%= render :partial => 'users/sidenav', :locals => {:user => @authenticated} %>
  <div class="col-md-10 col-md-pull-2">
      <% if @picture.id.present? %>
        <h2>Edit Picture</h2>
      <% else %>
        <h2>New Picture</h2>
      <% end %>

      <% if @picture.errors.any? %>
        <ol>
          <% @picture.errors.full_messages.each do |msg| %>
            <li class="alert alert-warning"><%= msg %></div>
          <% end %>
        </ol>
      <% end %>

      <%= form_for @picture, :html => {:multipart => true} do |f| %>

        <div class='form-group'>
          <%= f.label :name %>
          <%= f.text_field :name, :autofocus => true, :class => 'form-control', :placeholder => 'Optional' %>
        </div>
        <%= image_tag @picture.picture_url if @picture.picture? %>
        <div class='form-group'>
          <%= f.label :picture %>
          <%= f.file_field :picture %>
        </div>
        <div class='form-group'>
          <%= f.label :remote_picture_url, "Or Picture Url" %>
          <%= f.text_field :remote_picture_url, :class => 'form-control', :placeholder => 'Required if you have not uploaded a file above' %>
        </div>
        <div class='form-group'>
          <%= f.label :description %>
          <%= f.text_field :description, :class => 'form-control', :placeholder => 'Optional' %>
        </div>
        <%= f.submit %>

      <% end %>
  </div>

</div>

app/views/pictures/show.html.erb
<div class="row">

  <%= render :partial => 'users/sidenav', :locals => {:user => @authenticated} %>
  <div class="col-md-10 col-md-pull-2">

    <div class="show_pic_page">
      <h2><%= @picture.name %></h2>
      <h5><%= link_to @picture.user.username, user_path(@picture.user) %> </h5>
      <div class="show_picture">
      <%= image_tag @picture.picture_url %>
      </div>
      <p><%= @picture.description %></p>

      <div class="row">
        <div class="col-md-1">
                <% if @picture.id.in? @authenticated.favourites.map &:picture_id %>
                  <%= button_to 'Unfavourite', favourite_path(@picture), :method => 'delete' %>
                <% else %>
                  <%= button_to 'Favourite!', favourite_path(@picture), :method => 'get', :class => 'pull-left' %>
                <% end %>
        </div>

        <% if @picture.user_id == @authenticated.id %>
        <div class="col-md-10">
            <%= link_to 'Edit Picture', edit_picture_path(@picture), :class => 'show_pic_btn ed' %>
        </div>
        <div class="col-md-1">
          <%= button_to 'Delete Picture', picture_path(@picture), :method => 'delete', :confirm => 'Are you sure you want to delete this picture?', :class => 'pull-right' %>
        </div>
        <% end %>

      </div>
    </div>
  </div>
</div>