config/routes.rb
PictureApp::Application.routes.draw do
  root :to => 'pages#home'
  get '/about' => 'pages#about'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  get '/search' => 'search#search'


  get     '/categories/add_user_to_categories/:id/edit' => 'categories#edit_user_categories', :as => 'edit_user_to_categories'
  post     '/categories/add_user_to_categories' => 'categories#add_user_to_categories'
  get    '/categories/:id/edit' => 'categories#edit', :as => 'edit_category'
  get    '/categories/new' => 'categories#new', :as => 'new_category'
  post    '/categories/:id' => 'categories#create'
  get    '/categories/:id' => 'categories#show', :as => 'category'
  put    '/categories/:id' => 'categories#update'
  delete '/categories/:id' => 'categories#destroy'


  get '/picture/:id/favourite' => 'pictures#favourite', :as => 'favourite'
  delete '/picture/:id/favourite' => 'pictures#destroy_favourite', :as => 'destroy_favourite'

  get '/users/:id/favourites' => 'users#favourites', :as => 'favourites'


  resources :pictures
  resources :users, :except => [:edit] do
    collection do
      get 'edit'
    end
  end
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  owner_id   :integer
#

class Category < ActiveRecord::Base
  attr_accessible :name, :owner_id


  has_and_belongs_to_many :users


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def new
    @category = Category.new
    @users = User.all
  end

  def create
    category = Category.create :name => params[:new_category], :owner_id => @authenticated.id

    params[:user].each do |user_id|
      user = User.find(user_id)
      user.categories << category
    end

    redirect_to category_path(@category)
  end


  def edit
    @category = Category.find params[:id]
    @users = User.all
  end

  def update
    @category = Category.find params[:id]

    @category.users = []

    params[:user].each do |user_id|
      user = User.find(user_id)
      if @category.owner_id == @authenticated.id
        user.categories << @category
      end
    end
    redirect_to category_path(@category)
  end

  def show
    @category = Category.find params[:id]
  end

  def destroy
    category = Category.find params[:id]
    if category.owner_id != @authenticated.id
      redirect_to root_path
    end
    category.destroy
    redirect_to user_path(@authenticated)
  end

  def edit_user_categories
    @categories = Category.all
    @user = User.find params[:id]
  end

  def add_user_to_categories
    user = User.find params[:member_id]

    # remove the user from all authenticated's categories
    user.categories = user.categories.where('owner_id != ?', @authenticated.id)

    if params[:new_category].present?
      new_category = Category.create(:name => params[:new_category],
                                     :owner_id => @authenticated.id)
      new_category.users << user
    end
    params[:category].each do |category_id|
      category = Category.find(category_id)
      if category.owner_id == @authenticated.id
        category.users << user
      end
    end
    redirect_to user_path(user)
  end

end

app/views/categories/edit.html.erb
<div class="row">
  <%= render :partial => 'users/sidenav', :locals => {:user => @authenticated} %>
  <div class="col-md-10 col-md-pull-2">
      <h1>Edit Category</h1>

      <% if @category.errors.any? %>
        <ol>
          <% @category.errors.full_messages.each do |msg| %>
            <li class="alert alert-warning"><%= msg %></div>
          <% end %>
        </ol>
      <% end %>




      <%= form_tag "/categories/#{@category.id}", :method => 'put' do %>
        <input type="hidden" name="id" value="<%= @category.id %>">

        <h4>Select who to add this category:</h4>
          <% @users.each do |user| %>
            <% if @category.owner_id == @authenticated.id %>
              <%= check_box_tag "user[]", user.id, user.id.in?(@category.user_ids) %><%= user.username %>
            <% end %>
          <% end %>
        <br>
        <%= submit_tag("Submit") %>
      <% end %>
  </div>

</div>

app/views/categories/edit_user_categories.html.erb
<div class="row">
  <%= render :partial => 'users/sidenav', :locals => {:user => @authenticated} %>
  <div class="col-md-10 col-md-pull-2">
      <h2>Add this Glimpsed user to Categories</h2>



      <%= form_tag "/categories/add_user_to_categories", :method => 'post' do %>
        <input type="hidden" name="member_id" value="<%= @user.id %>">
        <%= label_tag(:new_category, "Create a New Category:") %>
        <%= text_field_tag(:new_category) %>
        <br>
          <h4>Or Select from your existing categories:</h4>
          <% @categories.each do |category| %>
            <% if category.owner_id == @authenticated.id %>
              <%= check_box_tag "category[]", category.id, @user.id.in?(category.user_ids) %><%= category.name %>
            <% end %>
          <% end %>
          <br>
        <%= submit_tag("Submit") %>
      <% end %>
  </div>

</div>

app/views/categories/new.html.erb
<div class="row">
  <%= render :partial => 'users/sidenav', :locals => {:user => @authenticated} %>
  <div class="col-md-10 col-md-pull-2">
      <h2>New Category</h2>


      <% if @category.errors.any? %>
        <ol>
          <% @category.errors.full_messages.each do |msg| %>
            <li class="alert alert-warning"><%= msg %></div>
          <% end %>
        </ol>
      <% end %>



      <%= form_tag "/categories/new_category", :method => 'post' do %>
        <input type="hidden" name="id" value="new_category">
        <%= label_tag(:new_category, "Create a New Category:") %>
        <%= text_field_tag(:new_category) %>
        <br>
        <h3>Select who to add this category:</h3>
          <% @users.each do |user| %>
              <h4><%= check_box_tag "user[]", user.id %><%= user.username %></h4>
          <% end %>
        <br>
        <%= submit_tag("Submit") %>
      <% end %>
  </div>

</div>

app/views/categories/show.html.erb
<div class="row">
  <%= render :partial => 'users/sidenav', :locals => {:user => @authenticated} %>

  <div class="col-md-10 col-md-pull-2">
    <h2>Category: <%= @category.name %></h2>

    <div class="pull-right">
      <% if @category.owner_id == @authenticated.id %>
        <%= link_to 'Edit Category', edit_category_path(@category) %>
        <%= button_to 'Delete Category', category_path(@category), :method => 'delete', :confirm => 'Are you sure you want to delete this category?' %>
      <% end %>
    </div>

    <div class="category_display">
      <h4>Users within this category</h4>
        <ul>
          <% @category.users.each do |user| %>
              <li><%= link_to user.username, user_path(user) %></li>
          <% end %>
        </ul>

      <h4>Pictures within this category</h4>
    </div>
    <% @category.users.each do |user| %>
       <%= render :partial => 'pictures/picture', :collection => user.pictures %>
    <% end %>
  </div>

</div>